//! BN254 constants for the 4×u64 Montgomery representation (R = 2^256).
//! Generated by a script from the field moduli; verified against arkworks in tests.

/// FP: modulus limbs (little-endian).
pub const FP_MODULUS: [u64; 4] = [
    0x3c208c16d87cfd47,
    0x97816a916871ca8d,
    0xb85045b68181585d,
    0x30644e72e131a029,
];
/// FP: R mod modulus (the Montgomery form of 1).
pub const FP_R: [u64; 4] = [
    0xd35d438dc58f0d9d,
    0x0a78eb28f5c70b3d,
    0x666ea36f7879462c,
    0x0e0a77c19a07df2f,
];
/// FP: R^2 mod modulus (converts canonical to Montgomery by one multiplication).
pub const FP_R2: [u64; 4] = [
    0xf32cfc5b538afa89,
    0xb5e71911d44501fb,
    0x47ab1eff0a417ff6,
    0x06d89f71cab8351f,
];
/// FP: -modulus^-1 mod 2^64 (the Montgomery reduction constant).
pub const FP_INV: u64 = 0x87d20782e4866389;
/// FP: (modulus - 2) limbs, the exponent for Fermat inversion.
pub const FP_MODULUS_MINUS_2: [u64; 4] = [
    0x3c208c16d87cfd45,
    0x97816a916871ca8d,
    0xb85045b68181585d,
    0x30644e72e131a029,
];

/// FR: modulus limbs (little-endian).
pub const FR_MODULUS: [u64; 4] = [
    0x43e1f593f0000001,
    0x2833e84879b97091,
    0xb85045b68181585d,
    0x30644e72e131a029,
];
/// FR: R mod modulus (the Montgomery form of 1).
pub const FR_R: [u64; 4] = [
    0xac96341c4ffffffb,
    0x36fc76959f60cd29,
    0x666ea36f7879462e,
    0x0e0a77c19a07df2f,
];
/// FR: R^2 mod modulus (converts canonical to Montgomery by one multiplication).
pub const FR_R2: [u64; 4] = [
    0x1bb8e645ae216da7,
    0x53fe3ab1e35c59e3,
    0x8c49833d53bb8085,
    0x0216d0b17f4e44a5,
];
/// FR: -modulus^-1 mod 2^64 (the Montgomery reduction constant).
pub const FR_INV: u64 = 0xc2e1f593efffffff;
/// FR: (modulus - 2) limbs, the exponent for Fermat inversion.
pub const FR_MODULUS_MINUS_2: [u64; 4] = [
    0x43e1f593efffffff,
    0x2833e84879b97091,
    0xb85045b68181585d,
    0x30644e72e131a029,
];

/// Fr: two-adicity of r - 1 (r - 1 = 2^28 · odd).
pub const FR_TWO_ADICITY: u32 = 28;
/// Fr: a primitive 2^28-th root of unity, canonical form: 5^((r-1)/2^28) with 5 the multiplicative generator.
pub const FR_TWO_ADIC_ROOT_CANONICAL: [u64; 4] = [
    0x9bd61b6e725b19f0,
    0x402d111e41112ed4,
    0x00e0a7eb8ef62abc,
    0x2a3c09f0a58a7e85,
];
/// Fr: the multiplicative generator (canonical), as in arkworks.
pub const FR_GENERATOR_CANONICAL: [u64; 4] = [
    0x0000000000000005,
    0x0000000000000000,
    0x0000000000000000,
    0x0000000000000000,
];

/// G1: the curve constant b = 3 (canonical).
pub const G1_B_CANONICAL: [u64; 4] = [
    0x0000000000000003,
    0x0000000000000000,
    0x0000000000000000,
    0x0000000000000000,
];
/// G2: the twist constant b' = 3/(9+u) in Fp2, real part (canonical).
pub const G2_B_C0_CANONICAL: [u64; 4] = [
    0x3267e6dc24a138e5,
    0xb5b4c5e559dbefa3,
    0x81be18991be06ac3,
    0x2b149d40ceb8aaae,
];
/// G2: the twist constant, coefficient of `u` (canonical).
pub const G2_B_C1_CANONICAL: [u64; 4] = [
    0xe4a2bd0685c315d2,
    0xa74fa084e52d1852,
    0xcd2cafadeed8fdf4,
    0x009713b03af0fed4,
];
